### ISSUE TITLE
Eclipse will not successfully activate knip 

### ISSUE THREAD

**Issue by Mereep** [knime-ip/knip-sdk-setup#15] opened 2018-10-29 14:52 UTC
Hello, 

I tried to build a node dealing with KNIPS-Images. I started building the node against latest nightly, which builds correctly. 

Now I tried to include this repository. But for some reason I cannot activate the dev-nightly. It will throw tons of errors no matter how often I  press reload and update button. When switching back to the vanilla knime version, it works again. 

Is the build as-is right now working? Since this is my very first node and I also have almost zero experience with eclipse, this is very hard to fix.

If I may guess its somehow related to the "enterprise server" units. These are not available. But thats just a wild guess.

![target_probs](https://user-images.githubusercontent.com/7294792/47657967-6d48dd00-db92-11e8-8fad-b7d56c6024af.png)

**Comment by gab1one** [comment] 2018-10-30 09:59
Hi @Mereep,
This is indeed caused by changes in the available plugins and I will fix this ASAP.
Anyway as an external developer you want to use the `knip-sdk-full-3.6.target` which targets the latest released versions of KNIME and KNIP (then you also do not need to import all the knip projects into your workspace) the `knip-sdk-dev-nightly` points at nightly KNIME and is much more unstable.

**Comment by gab1one** [comment] 2018-10-30 10:14
Fixed in c4392b8faa35a137c761c761155ee536787156ff

**Closed as completed by gab1one** 2018-10-30 10:14 UTC
